### ISSUE TITLE
Network Tokens and WebRTC QoS

### ISSUE THREAD

**Issue by yiannisy** [w3c/webrtc-priority#13]
Hi,

Not sure if this is the right place, but wanted to bring into your attention network tokens (https://networktokens.org), a new project/IETF I-D that might be relevant with WebRTC and QoS. 

In a nutshell: Network tokens are an open and secure method for end users and application providers to coordinate with the network about how their traffic is treated ( e.g., to access a 5G slice, a firewall whitelist, a zero-rating, or a QoS service ). Network Tokens replace complex, insecure, and privacy-invasive DPI application signatures with a deterministic and unified mechanism to build network services, and complement DSCP codepoints across network boundaries.

We have a prototype implementation using network tokens as part of WebRTC, and I'd be very interested to understand what's the best way to engage with the WebRTC group and get feedback/guidance on next steps.

**Comment by alvestrand** [comment]
This seems to be out of scope for this document, but may be in scope for webrtc-extensions.
