### ISSUE TITLE
Prepare spec for TAG review

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-priority#6]
In terms of spec text, this requires merging #5.
We have a review questionnaire. Must check what other things need filling out.

**Comment by alvestrand** [comment]
#5 is now merged, and I have updated the explainer to start at the beginning. Seeking advice from @dontcallmedom on what more is needed. (I didn't find a bug either here or on the TAG repo indicating TAG feedback).

**Comment by dontcallmedom** [comment]
https://github.com/w3ctag/design-reviews/issues/465#issuecomment-587495443 is where the TAG feedback is
