### ISSUE TITLE
Move wpt tests to new directory

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-priority#8]
By the principles of wpt test naming, tests that reference "priority" should now be in a new webrtc-dscp-exp directory.

(which brings to mind: should we rename this spec "webrtc-priority"?)

**Comment by foolip** [comment]
I came here trying to deal with https://github.com/web-platform-tests/wpt/pull/21223.

What does the "exp" in the shortname mean? If you are going to rename the spec, it'd be great if that happens soon, as renames need to be handled manually in reffy-reports and wpt.

**Comment by dontcallmedom** [comment]
`exp` was for experimentation I believe. I took the aciton yesterday to rename it to webrtc-priority. I'm happy to do that now if this is a good time wrt reffy/wpt - in other words, I'll do it as soon as I see a green light from you

**Comment by foolip** [comment]
Now would be a good time, since I'd like to add a new directory in wpt, and then matching the spec name. Green light assuming @alvestrand also approves.

**Comment by dontcallmedom** [comment]
name updated @foolip

**Comment by foolip** [comment]
Thanks @dontcallmedom! What will happen to https://www.w3.org/TR/webrtc-dscp/? That's what's listed in [Reffy](https://github.com/tidoust/reffy/blob/edcf66086f73b707d8f4f2d347c1ef318101a59d/src/specs/specs-idl.json#L142) but can a TR name change? It's bit of a nuisance when TR name and GitHub repo name don't match...

**Comment by dontcallmedom** [comment]
I plan to have the shortname updated (to webrtc-priority as well), but that will require a bit more time (hopefully sometimes next week)

**Comment by foolip** [comment]
Alright, good thing it's not set in stone :) Can you ping me or @tidoust when it's updated so we can update the URL in Reffy?

**Comment by dontcallmedom** [comment]
The new TR URL is out @foolip https://www.w3.org/TR/webrtc-priority

**Comment by foolip** [comment]
Thanks @dontcallmedom! The rename has reached WPT: https://github.com/web-platform-tests/wpt/pull/21442

**Comment by alvestrand** [comment]
The existing tests are now moved (extracted from the corresponding wpt/webrtc tests).

**Comment by alvestrand** [comment]
Moved as https://chromium-review.googlesource.com/c/chromium/src/+/2201757 (May 14 2020)
